// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: exercises.sql

package db

import (
	"context"
)

const createExerciseRecommendation = `-- name: CreateExerciseRecommendation :one
INSERT INTO exercise_recommendations (
    patient_id, prediction_id, plan
) VALUES ($1, $2, $3)
RETURNING id, patient_id, prediction_id, plan, created_at
`

type CreateExerciseRecommendationParams struct {
	PatientID    int64  `json:"patient_id"`
	PredictionID int64  `json:"prediction_id"`
	Plan         []byte `json:"plan"`
}

func (q *Queries) CreateExerciseRecommendation(ctx context.Context, arg CreateExerciseRecommendationParams) (ExerciseRecommendation, error) {
	row := q.db.QueryRow(ctx, createExerciseRecommendation, arg.PatientID, arg.PredictionID, arg.Plan)
	var i ExerciseRecommendation
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.PredictionID,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const createExerciseTemplate = `-- name: CreateExerciseTemplate :one
INSERT INTO exercise_templates (
    name, intensity, description, duration_min, freq_per_week, target_risk_level, tags
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, name, intensity, description, duration_min, freq_per_week, target_risk_level, tags
`

type CreateExerciseTemplateParams struct {
	Name            string   `json:"name"`
	Intensity       string   `json:"intensity"`
	Description     string   `json:"description"`
	DurationMin     int32    `json:"duration_min"`
	FreqPerWeek     int32    `json:"freq_per_week"`
	TargetRiskLevel string   `json:"target_risk_level"`
	Tags            []string `json:"tags"`
}

func (q *Queries) CreateExerciseTemplate(ctx context.Context, arg CreateExerciseTemplateParams) (ExerciseTemplate, error) {
	row := q.db.QueryRow(ctx, createExerciseTemplate,
		arg.Name,
		arg.Intensity,
		arg.Description,
		arg.DurationMin,
		arg.FreqPerWeek,
		arg.TargetRiskLevel,
		arg.Tags,
	)
	var i ExerciseTemplate
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Intensity,
		&i.Description,
		&i.DurationMin,
		&i.FreqPerWeek,
		&i.TargetRiskLevel,
		&i.Tags,
	)
	return i, err
}

const getExerciseRecommendationByPrediction = `-- name: GetExerciseRecommendationByPrediction :one
SELECT id, patient_id, prediction_id, plan, created_at FROM exercise_recommendations
WHERE prediction_id = $1
LIMIT 1
`

func (q *Queries) GetExerciseRecommendationByPrediction(ctx context.Context, predictionID int64) (ExerciseRecommendation, error) {
	row := q.db.QueryRow(ctx, getExerciseRecommendationByPrediction, predictionID)
	var i ExerciseRecommendation
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.PredictionID,
		&i.Plan,
		&i.CreatedAt,
	)
	return i, err
}

const listExerciseRecommendationsByPatient = `-- name: ListExerciseRecommendationsByPatient :many
SELECT id, patient_id, prediction_id, plan, created_at FROM exercise_recommendations
WHERE patient_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListExerciseRecommendationsByPatientParams struct {
	PatientID int64 `json:"patient_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListExerciseRecommendationsByPatient(ctx context.Context, arg ListExerciseRecommendationsByPatientParams) ([]ExerciseRecommendation, error) {
	rows, err := q.db.Query(ctx, listExerciseRecommendationsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseRecommendation
	for rows.Next() {
		var i ExerciseRecommendation
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.PredictionID,
			&i.Plan,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExerciseTemplates = `-- name: ListExerciseTemplates :many
SELECT id, name, intensity, description, duration_min, freq_per_week, target_risk_level, tags FROM exercise_templates
ORDER BY name ASC
`

func (q *Queries) ListExerciseTemplates(ctx context.Context) ([]ExerciseTemplate, error) {
	rows, err := q.db.Query(ctx, listExerciseTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseTemplate
	for rows.Next() {
		var i ExerciseTemplate
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Intensity,
			&i.Description,
			&i.DurationMin,
			&i.FreqPerWeek,
			&i.TargetRiskLevel,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
