// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ExerciseRecommendation struct {
	ID           int64              `json:"id"`
	PatientID    int64              `json:"patient_id"`
	PredictionID int64              `json:"prediction_id"`
	Plan         []byte             `json:"plan"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type ExerciseTemplate struct {
	ID              int64    `json:"id"`
	Name            string   `json:"name"`
	Intensity       string   `json:"intensity"`
	Description     string   `json:"description"`
	DurationMin     int32    `json:"duration_min"`
	FreqPerWeek     int32    `json:"freq_per_week"`
	TargetRiskLevel string   `json:"target_risk_level"`
	Tags            []string `json:"tags"`
}

type Patient struct {
	ID        int64              `json:"id"`
	UserID    string             `json:"user_id"`
	Name      string             `json:"name"`
	Gender    int16              `json:"gender"`
	Dob       pgtype.Date        `json:"dob"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Prediction struct {
	ID          int64              `json:"id"`
	PatientID   int64              `json:"patient_id"`
	Probability float64            `json:"probability"`
	RiskLabel   string             `json:"risk_label"`
	RawFeatures []byte             `json:"raw_features"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
