// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"
)

const countReportsByPatient = `-- name: CountReportsByPatient :one
SELECT COUNT(*) FROM reports
WHERE patient_id = $1
`

func (q *Queries) CountReportsByPatient(ctx context.Context, patientID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countReportsByPatient, patientID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReport = `-- name: CreateReport :one
INSERT INTO reports (patient_id, filename, file_url, recipients)
VALUES ($1, $2, $3, $4)
RETURNING id, patient_id, filename, file_url, recipients, created_at
`

type CreateReportParams struct {
	PatientID  int64  `json:"patient_id"`
	Filename   string `json:"filename"`
	FileUrl    string `json:"file_url"`
	Recipients []byte `json:"recipients"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.PatientID,
		arg.Filename,
		arg.FileUrl,
		arg.Recipients,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Filename,
		&i.FileUrl,
		&i.Recipients,
		&i.CreatedAt,
	)
	return i, err
}

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports
WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, patient_id, filename, file_url, recipients, created_at FROM reports
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetReportByID(ctx context.Context, id int64) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Filename,
		&i.FileUrl,
		&i.Recipients,
		&i.CreatedAt,
	)
	return i, err
}

const listReportsByPatient = `-- name: ListReportsByPatient :many
SELECT id, patient_id, filename, file_url, recipients, created_at FROM reports
WHERE patient_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReportsByPatientParams struct {
	PatientID int64 `json:"patient_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListReportsByPatient(ctx context.Context, arg ListReportsByPatientParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByPatient, arg.PatientID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.PatientID,
			&i.Filename,
			&i.FileUrl,
			&i.Recipients,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReportRecipients = `-- name: UpdateReportRecipients :one
UPDATE reports
SET recipients = $2
WHERE id = $1
RETURNING id, patient_id, filename, file_url, recipients, created_at
`

type UpdateReportRecipientsParams struct {
	ID         int64  `json:"id"`
	Recipients []byte `json:"recipients"`
}

func (q *Queries) UpdateReportRecipients(ctx context.Context, arg UpdateReportRecipientsParams) (Report, error) {
	row := q.db.QueryRow(ctx, updateReportRecipients, arg.ID, arg.Recipients)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.PatientID,
		&i.Filename,
		&i.FileUrl,
		&i.Recipients,
		&i.CreatedAt,
	)
	return i, err
}
