// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package db

import (
	"context"
)

const getRiskDistribution = `-- name: GetRiskDistribution :many
WITH latest_predictions AS (
    SELECT DISTINCT ON (p.patient_id) p.risk_label
    FROM predictions p
    JOIN patients pa ON p.patient_id = pa.id
    WHERE pa.user_id = $1
    ORDER BY p.patient_id, p.created_at DESC
)
SELECT 
    risk_label,
    COUNT(*) AS count
FROM latest_predictions
GROUP BY risk_label
`

type GetRiskDistributionRow struct {
	RiskLabel string `json:"risk_label"`
	Count     int64  `json:"count"`
}

func (q *Queries) GetRiskDistribution(ctx context.Context, userID string) ([]GetRiskDistributionRow, error) {
	rows, err := q.db.Query(ctx, getRiskDistribution, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRiskDistributionRow
	for rows.Next() {
		var i GetRiskDistributionRow
		if err := rows.Scan(&i.RiskLabel, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalPatients = `-- name: GetTotalPatients :one
SELECT COUNT(*) FROM patients
WHERE user_id = $1
`

func (q *Queries) GetTotalPatients(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPatients, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getTotalPredictions = `-- name: GetTotalPredictions :one
SELECT COUNT(*) 
FROM predictions p
JOIN patients pa ON p.patient_id = pa.id
WHERE pa.user_id = $1
`

func (q *Queries) GetTotalPredictions(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalPredictions, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
